import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { createClient } from '@supabase/supabase-js';
import { createTestUsers, cleanupTestUsers, adminClient, SUPABASE_URL, ANON_KEY, type TestUser } from './helpers/testUsers';
import { setupGroup, type GroupRow } from './helpers/scenarios';

/** Matches the constant in 20260813130000_invite_code_rate_limit.sql. */
const MISS_LIMIT = 10;

/**
 * A 4-character code that is format-valid but can never belong to a real group, under either
 * generator this project has had: codes minted before 20260813140000 came out of md5() and so are
 * hex (no Z possible), and codes minted after it come from an alphabet with no 0 and no 1. A code
 * carrying both a Z and a 0 can't have been generated by either.
 */
function bogusCode(n: number): string {
  return `Z0${n.toString().padStart(2, '0')}`;
}

async function attemptRow(userId: string) {
  const { data } = await adminClient.from('invite_code_attempts').select('*').eq('user_id', userId).maybeSingle();
  return data as { user_id: string; miss_count: number; window_ends_at: string } | null;
}

/** Ends the caller's current window without touching the app's own logic, so the next miss starts a fresh one. */
async function expireWindow(userId: string) {
  const { error } = await adminClient
    .from('invite_code_attempts')
    .update({ window_ends_at: new Date(Date.now() - 60_000).toISOString() })
    .eq('user_id', userId);
  if (error) throw new Error(`expireWindow: ${error.message}`);
}

describe('invite code rate limit', () => {
  let users: Record<string, TestUser>;
  let group: GroupRow;

  beforeAll(async () => {
    users = await createTestUsers('rate', ['owner', 'guesser', 'prober']);
    group = await setupGroup(users.owner, []);
  });

  afterAll(async () => {
    await cleanupTestUsers(users);
  });

  test('a wrong code is a miss, not an error, and the budget runs out after ten of them', async () => {
    for (let i = 0; i < MISS_LIMIT; i++) {
      const { data, error } = await users.guesser.client.rpc('get_group_by_invite_code', { p_invite_code: bogusCode(i) });
      expect(error).toBeNull();
      expect(data).toEqual([]);
    }

    expect((await attemptRow(users.guesser.id))?.miss_count).toBe(MISS_LIMIT);

    const { error: blockedErr } = await users.guesser.client.rpc('get_group_by_invite_code', { p_invite_code: bogusCode(99) });
    expect(blockedErr?.message).toMatch(/invalid_operation/);
    expect(blockedErr?.message).toMatch(/too many invite code tries/);

    // Refused before the lookup, so a blocked guess doesn't even get counted.
    expect((await attemptRow(users.guesser.id))?.miss_count).toBe(MISS_LIMIT);
  });

  test('the budget is shared with join_group, so guessing at previews also closes the door on joining', async () => {
    const { error } = await users.guesser.client.rpc('join_group', {
      p_invite_code: group.invite_code,
      p_nickname: 'guesser',
    });
    expect(error?.message).toMatch(/too many invite code tries/);

    // ...and once the window lapses, the same real code works normally again.
    await expireWindow(users.guesser.id);
    const { data, error: joinErr } = await users.guesser.client.rpc('join_group', {
      p_invite_code: group.invite_code,
      p_nickname: 'guesser',
    });
    expect(joinErr).toBeNull();
    expect(data).not.toBeNull();
  });

  test('join_group returns no rows (never a raise) for a code that matches nothing, and counts it', async () => {
    const before = (await attemptRow(users.prober.id))?.miss_count ?? 0;

    const { data, error } = await users.prober.client.rpc('join_group', { p_invite_code: bogusCode(50), p_nickname: 'prober' });
    expect(error).toBeNull();
    // Zero rows, not a null row: a `returns memberships` function returning NULL would serialize
    // as an object of all-null columns, which every `if (!data)` check in the app would miss.
    expect(data).toEqual([]);

    expect((await attemptRow(users.prober.id))?.miss_count).toBe(before + 1);
  });

  test('a code that really exists never counts, however many times it is used', async () => {
    await adminClient.from('invite_code_attempts').delete().eq('user_id', users.prober.id);

    for (let i = 0; i < MISS_LIMIT + 5; i++) {
      const { data, error } = await users.prober.client.rpc('get_group_by_invite_code', { p_invite_code: group.invite_code });
      expect(error).toBeNull();
      expect((data as unknown[]).length).toBe(1);
    }

    expect(await attemptRow(users.prober.id)).toBeNull();
  });

  test('a minted code avoids the characters people misread, at both the create and regenerate call sites', async () => {
    // 2-9 and A-Z without I or O: no 0/O or 1/I confusion when a code is read out loud or typed
    // off a card. Codes minted before 20260813140000 are hex and would fail this on purpose,
    // which is why it only ever runs against codes this suite just created.
    const MINTED = /^[2-9A-HJ-NP-Z]{4}$/;
    expect(group.invite_code).toMatch(MINTED);

    const fresh = await setupGroup(users.owner, []);
    const { error } = await users.owner.client.rpc('regenerate_invite_code', { p_group_id: fresh.id });
    expect(error).toBeNull();

    const { data: row } = await adminClient.from('groups').select('invite_code').eq('id', fresh.id).single();
    expect(row!.invite_code).not.toBe(fresh.invite_code);
    expect(row!.invite_code).toMatch(MINTED);
  });

  test('the counter is invisible to the client it counts', async () => {
    const { data, error } = await users.prober.client.from('invite_code_attempts').select('*');
    // Zero-policy table: RLS on with no policy, so a client read is empty rather than forbidden.
    expect(data ?? []).toEqual([]);
    expect(error === null || error.code === '42501').toBe(true);
  });

  test('get_group_by_invite_code and join_group reject a caller with no session at all', async () => {
    const anonClient = createClient(SUPABASE_URL!, ANON_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });

    const { error: previewErr } = await anonClient.rpc('get_group_by_invite_code', { p_invite_code: group.invite_code });
    expect(previewErr?.code).toBe('42501');

    const { error: joinErr } = await anonClient.rpc('join_group', { p_invite_code: group.invite_code, p_nickname: 'nope' });
    expect(joinErr?.code).toBe('42501');
  });
});

/**
 * invite_code_exists() is the anon-callable sibling that lets /join/[code] reject a bad code
 * before bouncing a signed-out visitor into the login flow at all (see
 * 20260814110000_anon_invite_code_exists.sql). It only ever answers true/false, and it's rate
 * limited by IP (via a client-supplied x-forwarded-for header, set here to simulate distinct
 * visitors) rather than by account, since an anonymous caller has no auth.uid().
 */
describe('anonymous invite code existence check', () => {
  const anonClient = createClient(SUPABASE_URL!, ANON_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });
  let owner: TestUser;
  let group: GroupRow;

  beforeAll(async () => {
    const users = await createTestUsers('anonx', ['owner']);
    owner = users.owner;
    group = await setupGroup(owner, []);
  });

  afterAll(async () => {
    await cleanupTestUsers({ owner });
  });

  function fakeIp(n: number): string {
    return `198.51.100.${n}`;
  }

  test('a bogus code returns false, no account required', async () => {
    const { data, error } = await anonClient
      .rpc('invite_code_exists', { p_invite_code: bogusCode(80) })
      .setHeader('x-forwarded-for', fakeIp(1));
    expect(error).toBeNull();
    expect(data).toBe(false);
  });

  test('a real code returns true, without revealing anything beyond that', async () => {
    const { data, error } = await anonClient
      .rpc('invite_code_exists', { p_invite_code: group.invite_code })
      .setHeader('x-forwarded-for', fakeIp(2));
    expect(error).toBeNull();
    expect(data).toBe(true);
  });

  test('misses are rate limited per IP, and the budget runs out after ten', async () => {
    const ip = fakeIp(3);
    for (let i = 0; i < MISS_LIMIT; i++) {
      const { data, error } = await anonClient
        .rpc('invite_code_exists', { p_invite_code: bogusCode(60 + i) })
        .setHeader('x-forwarded-for', ip);
      expect(error).toBeNull();
      expect(data).toBe(false);
    }

    const { error: blockedErr } = await anonClient
      .rpc('invite_code_exists', { p_invite_code: bogusCode(99) })
      .setHeader('x-forwarded-for', ip);
    expect(blockedErr?.message).toMatch(/invalid_operation/);
    expect(blockedErr?.message).toMatch(/too many invite code tries/);

    // A different visitor (different IP) has its own, untouched budget.
    const { data: freshData, error: freshErr } = await anonClient
      .rpc('invite_code_exists', { p_invite_code: bogusCode(70) })
      .setHeader('x-forwarded-for', fakeIp(4));
    expect(freshErr).toBeNull();
    expect(freshData).toBe(false);
  });

  test('a real code never counts against the IP budget, however many times it is checked', async () => {
    const ip = fakeIp(5);
    for (let i = 0; i < MISS_LIMIT + 5; i++) {
      const { data, error } = await anonClient
        .rpc('invite_code_exists', { p_invite_code: group.invite_code })
        .setHeader('x-forwarded-for', ip);
      expect(error).toBeNull();
      expect(data).toBe(true);
    }
  });

  test('the ip counter is invisible to the client it counts', async () => {
    const { data, error } = await anonClient.from('invite_code_ip_attempts').select('*');
    expect(data ?? []).toEqual([]);
    expect(error === null || error.code === '42501').toBe(true);
  });
});
